version: '3.7'
services:
  db:
    image: postgres:14.1-bullseye
    restart: always
    container_name: wishesdb
    expose:
      - 5433
    env_file:
      - .env
    ports:
      - ${DB_PORT}:5432
    volumes:
      - psql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  psql-data:
